# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 814eb2ed9784df4485f49100e318ecc463ed42c8dd94ddaa022cd2809046920d4b296487ade4dc4529c1ccbe2cea2a5f6acf170cea7095032ae2201ef69c31f6

test:
  secret_key_base: 2be4389ddc3f994b51143c8a6d276aebb960b7c7753a9ff2adc308bb3920197c2a8de2045771ac0b4601dcc6b6ded1b1cfaebf6fb80cf9ba33e6c03d117ad46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
